### ISSUE TITLE
无法加入电报组，邀请过期，无法加入

### ISSUE THREAD

**Issue by marqueritelynch** [blockchaindev90/BSCTokenSniper#17]
Unable to join the telegram group, invite expiration, unable to join

**Comment by marqueritelynch** [comment]
Unable to join the telegram group, invite expiration, unable to join

**Comment by marqueritelynch** [comment]
https://t.me/+KXvQjzlHv8c2NGU1

**Comment by marqueritelynch** [comment]
BSCTokenSniper | Loading...[22:31:30.680] [Info] Web3 successfully connected
Traceback (most recent call last):
  File "BSCTokenSniper.py", line 310, in <module>
  File "BSCTokenSniper.py", line 306, in updateTitle
  File "web3\module.py", line 53, in caller
  File "web3\method.py", line 202, in process_params
  File "eth_utils\functional.py", line 45, in inner
  File "web3\method.py", line 52, in _apply_request_formatters
  File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
  File "cytoolz/functoolz.pyx", line 505, in cytoolz.functoolz.Compose.__call__
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3\_utils\abi.py", line 799, in map_abi_data
  File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3\_utils\abi.py", line 833, in data_tree_map
  File "web3\_utils\decorators.py", line 30, in wrapped
  File "web3\_utils\formatters.py", line 89, in recursive_map
  File "web3\_utils\formatters.py", line 76, in map_collection
  File "web3\_utils\formatters.py", line 88, in recurse
  File "web3\_utils\decorators.py", line 30, in wrapped
  File "web3\_utils\formatters.py", line 90, in recursive_map
  File "web3\_utils\abi.py", line 830, in map_to_typed_data
  File "web3\_utils\normalizers.py", line 78, in wrapper
  File "web3\_utils\normalizers.py", line 196, in abi_address_to_hex
  File "web3\_utils\validation.py", line 182, in validate_address
web3.exceptions.InvalidAddress: ('Web3.py only accepts checksum addresses. The software that gave you this non-checksum address should be considered unsafe, please file it as a bug on their platform. Try using an ENS name instead. Or, if you must accept lower safety, use Web3.toChecksumAddress(lower_case_address).', '0xaf4d1596e9384b1fec15c1426c4f551ca6927118')
[12452] Failed to execute script 'BSCTokenSniper' due to unhandled exception!
